Deep-copy the LinkOCGAction object
The convertLinkActionToLink method deep-copies every poppler LinkAction
object into a Link object as used by the Qt5 frontend.  With one
exception: LinkOCGState objects are not deep-copied, but pointers to
them are stored instead.  This makes for a memory management that is
inconsistent, difficult to understand, and prone to memory errors.
The present patch introduces deep-copying for LinkOCGState objects
as well.