Include stdio.h from poppler-config.h
In poppler-config.h there is a check for __MINGW_PRINTF_FORMAT,
which is set by stdio.h.

This fixes this warning when compling with the mingw-w64-compiler:

XRef.cc: In member function 'virtual void
XRef::XRefTableWriter::writeEntry(Goffset, int, XRefEntryType)':
XRef.cc:1460:94: warning: unknown conversion type character 'l' in format [-Wformat=]
    outStr->printf("%010lli %05i %c\r\n", (long long)offset, gen, (type==xrefEntryFree)?'f':'n');
^
XRef.cc:1460:94: warning: format '%i' expects argument of type 'int', but argument 3 has type 'Goffset {aka long long int}' [-Wformat=]
XRef.cc:1460:94: warning: too many arguments for format [-Wformat-extra-args]

https://bugs.freedesktop.org/show_bug.cgi?id=79762