glib: fix ODR issue with enum
GCC trunk recently implemented https://wg21.link/P2115 in r16-3233-g7921bb4afcb7a3
which shows up when building Poppler as the following:
```
glib/poppler-document.cc:83:1: error: type ‘{enum:unsigned int{PROP_0}}’ violates the C++ One Definition Rule [-Werror=odr]
   83 | {
      | ^
glib/poppler-page.cc:46:1: note: an enum with different value name is defined in another translation unit
   46 | {
      | ^
glib/poppler-document.cc:85:5: note: name ‘PROP_TITLE’ differs from name ‘PROP_LABEL’ defined in another translation unit
   85 |     PROP_TITLE,
      |     ^
glib/poppler-page.cc:48:5: note: mismatching definition
   48 |     PROP_LABEL
      |     ^
```

Use an anonymous namespace for both enums to avoid the conflict.